
import { supabase, secondarySupabase } from '../src/supabaseClient';
import { Student, ClassCategory, TuitionRecord, UserProfile, LibraryResource, Event, AcademySettings, Expense } from '../types';
import { defaultAcademySettings } from '../mockData';

// Helper for UUID (Client handling if needed, though Supabase Auth handles User IDs)
const uuid = () => {
    if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID();
    return Date.now().toString(36) + Math.random().toString(36).substr(2);
}

export const PulseService = {
    // --- AUTH LAYER ---

    checkEmailExists: async (email: string): Promise<boolean> => {
        try {
            // Create a promise that rejects after 5 seconds
            const timeoutPromise = new Promise((_, reject) =>
                setTimeout(() => reject(new Error('Request timed out')), 5000)
            );

            // Race the supabase call against the timeout
            const { data, error } = await Promise.race([
                supabase
                    .from('profiles')
                    .select('email')
                    .eq('email', email)
                    .maybeSingle(),
                timeoutPromise
            ]) as any;

            console.timeEnd('checkEmailExists');
            if (error) {
                // If permission denied or other error, assume false to let Auth handle it
                return false;
            }
            return !!data;
        } catch (e) {
            // Timeout is expected if RLS blocks public access. 
            // We suppress the error and proceed to allow registration.
            return false;
        }
    },

    registerMaster: async (data: { name: string; email: string; password: string; academyName: string }) => {
        // 1. Sign Up with Supabase Auth
        // The trigger 'on_auth_user_created_master' will handle creating:
        // - The 'academies' record
        // - The 'profiles' record
        const { data: authData, error: authError } = await supabase.auth.signUp({
            email: data.email,
            password: data.password,
            options: {
                data: {
                    display_name: data.name,
                    role: 'master',
                    academy_name: data.academyName
                }
            }
        });

        if (authError) throw authError;

        // We can't immediately return a full user/academy object because:
        // 1. IDs are generated by the trigger
        // 2. We likely can't query them yet if RLS blocks read until email is verified
        // The AuthContext should handle this gracefully.

        return { user: null, academy: null };
    },

    registerStudent: async (data: {
        academyCode: string;
        email: string;
        password: string;
        name: string;
        cellPhone: string;
        age: number;
        birthDate: string;
        avatarUrl?: string;
        weight?: number;
        height?: number;
        bloodType?: string;
        guardianName: string;
        guardianEmail: string;
        guardianRelationship: string;
        guardianMainPhone: string;
        guardianSecondaryPhone?: string;
        guardianTertiaryPhone?: string;
        street: string;
        exteriorNumber: string;
        interiorNumber?: string;
        colony: string;
        zipCode: string;
    }) => {
        // 1. Find Academy
        const { data: academy, error: acadFetchError } = await supabase
            .from('academies')
            .select('*')
            .eq('code', data.academyCode)
            .single();

        if (acadFetchError || !academy) throw new Error("Código de academia inválido.");

        const initialAmount = Number(academy.settings?.paymentSettings?.monthlyTuition) || 0;

        // Prepare Payment Data (if any)
        let paymentData: any = null;
        if (initialAmount > 0) {
            const today = new Date();
            const monthName = today.toLocaleString('es-ES', { month: 'long' });
            const capitalizedMonth = monthName.charAt(0).toUpperCase() + monthName.slice(1);
            const concept = `Mensualidad ${capitalizedMonth}`;

            const lateFeeDay = academy.settings?.paymentSettings?.lateFeeDay || 10;
            const year = today.getFullYear();
            const month = String(today.getMonth() + 1).padStart(2, '0');
            const day = String(lateFeeDay).padStart(2, '0');
            const dueDate = `${year}-${month}-${day}`;

            paymentData = {
                initial_amount: initialAmount,
                due_date: dueDate,
                payment_concept: concept,
                payment_details: {
                    originalAmount: initialAmount,
                    penaltyAmount: 0,
                    type: 'charge',
                    description: 'Cuota mensual regular',
                    category: 'Mensualidad',
                    method: 'System',
                    canBePaidInParts: false
                }
            };
        }

        // Prepare Student Details used in Profile & Student Record
        const studentDetails = {
            age: data.age,
            birthDate: data.birthDate,
            cellPhone: data.cellPhone,
            weight: data.weight,
            height: data.height,
            bloodType: data.bloodType,
            guardian: {
                fullName: data.guardianName,
                email: data.guardianEmail,
                relationship: data.guardianRelationship,
                phones: {
                    main: data.guardianMainPhone,
                    secondary: data.guardianSecondaryPhone,
                    tertiary: data.guardianTertiaryPhone,
                },
                address: {
                    street: data.street,
                    exteriorNumber: data.exteriorNumber,
                    interiorNumber: data.interiorNumber,
                    colony: data.colony,
                    zipCode: data.zipCode
                }
            },
            program: 'Adults',
            joinDate: new Date().toLocaleDateString(),
            classesId: [],
            attendanceHistory: [],
            promotionHistory: []
        };

        // 2. SignUp
        // We now rely entirely on the Postgres Trigger to handle row creations securely.
        const { data: authData, error: authError } = await supabase.auth.signUp({
            email: data.email,
            password: data.password,
            options: {
                data: {
                    display_name: data.name,
                    role: 'student',
                    academy_id: academy.id,
                    avatar_url: data.avatarUrl || '',
                    initial_amount: initialAmount,
                    payment_due_date: paymentData?.due_date || null,
                    payment_concept: paymentData?.payment_concept || null,
                    student_details: studentDetails
                }
            }
        });

        if (authError) throw authError;
        if (!authData.user) throw new Error("No se pudo crear el usuario");

        // Return success object
        return {
            id: authData.user.id,
            email: data.email,
            name: data.name,
            role: 'student',
            academyId: academy.id,
            pendingVerification: !authData.session
        } as any;
    },

    createStudentAccountFromMaster: async (studentData: Student, defaultPassword = 'Pulse123!', initialAmount: number = 0) => {
        // We use the secondary client so we don't log out the Master!
        const details = { ...studentData };
        delete (details as any).id;
        delete (details as any).name;
        delete (details as any).email;
        delete (details as any).academyId;
        delete (details as any).balance;
        delete (details as any).status;
        const today = new Date();
        const monthName = today.toLocaleString('es-ES', { month: 'long' });
        const capitalizedMonth = monthName.charAt(0).toUpperCase() + monthName.slice(1);
        const concept = `Mensualidad ${capitalizedMonth}`;

        const { data, error } = await secondarySupabase.auth.signUp({
            email: studentData.email,
            password: defaultPassword,
            options: {
                data: {
                    role: 'student',
                    display_name: studentData.name,
                    academy_id: studentData.academyId,
                    student_details: details,
                    // Pass the actual amount configured in the academy settings
                    initial_amount: initialAmount,
                    payment_due_date: new Date().toISOString(),
                    payment_concept: concept
                }
            }
        });

        if (error) {
            console.error("Supabase Auth Error creating student:", error);
            throw error;
        }

        // The trigger automatically creates the profile and the student row
        // since rank_id and status might not be set accurately by trigger, we update it immediately:

        let attempts = 0;
        let authUserId = data?.user?.id;

        if (authUserId) {
            // Because triggers can be slightly asynchronous, we retry finding the student record up to 5 times
            let studentRecord = null;
            while (attempts < 5 && !studentRecord) {
                const { data: fetchStudent } = await supabase
                    .from('students')
                    .select('id')
                    .eq('user_id', authUserId)
                    .single();

                if (fetchStudent) {
                    studentRecord = fetchStudent;
                } else {
                    await new Promise(resolve => setTimeout(resolve, 800));
                    attempts++;
                }
            }

            if (studentRecord) {
                // Update rank and status to match what the Master chose in the form
                // But preserve 'debtor' if there's an initial amount!
                await supabase.from('students').update({
                    rank_id: studentData.rankId,
                    status: initialAmount > 0 ? 'debtor' : studentData.status
                }).eq('id', studentRecord.id);
            }
        }

        return data;
    },

    deleteFullStudentData: async (studentId: string) => {
        // Fetch the student name before deletion so we can stamp it on their retained paid payments
        const { data: student } = await supabase.from('students').select('name').eq('id', studentId).single();

        if (student) {
            const { data: paidPayments } = await supabase.from('payments').select('id, details').eq('student_id', studentId).eq('status', 'paid');

            if (paidPayments && paidPayments.length > 0) {
                // Keep a record of who the student was in the 'details' JSON before breaking the relation
                await Promise.all(paidPayments.map(p => {
                    const newDetails = { ...(p.details as any || {}), studentName: student.name };
                    return supabase.from('payments').update({ details: newDetails }).eq('id', p.id);
                }));
            }
        }

        // 1. Delete all payments that are NOT 'paid' (e.g. pending, overdue)
        await supabase.from('payments').delete().eq('student_id', studentId).neq('status', 'paid');

        // 2. Erase the student via RPC which deletes from auth.users safely cascading the deletion properly.
        const { error } = await supabase.rpc('delete_student_and_user', { p_student_id: studentId });

        if (error) {
            console.error("Error deleting student:", error);
            // Si quieres que la UI muestre un error y aborte en vez de continuar, puedes retornar false o lanzar un error.
            // Ojo: En este caso no paramos la ejecución del borrado local si consideramos que se borró al menos de "students".
            // Sin embargo, podemos lanzar una excepción para ser rígidos.
            throw error;
        }

        return true;
    },

    updateStudentCredentials: async (studentId: string, email?: string, password?: string) => {
        const { error } = await supabase.rpc('update_student_credentials', {
            p_student_id: studentId,
            p_new_email: email || null,
            p_new_password: password || null
        });
        if (error) {
            console.error("Supabase RPC update_student_credentials Error:", error);
            throw new Error(error.message || "Error al actualizar las credenciales.");
        }
    },

    login: async (email: string, pass: string): Promise<UserProfile> => {
        console.log("PulseService.login started for:", email);
        console.time('login');

        const { data, error } = await supabase.auth.signInWithPassword({
            email,
            password: pass
        });

        console.log("signInWithPassword result:", { user: data.user?.id, error });

        if (error) throw error;
        if (!data.user) throw new Error("Error de autenticación");

        // Fetch Profile
        console.log("Fetching profile for:", data.user.id);
        const { data: profile, error: profError } = await supabase
            .from('profiles')
            .select('*')
            .eq('id', data.user.id)
            .single();

        console.log("Profile fetch result:", { profile, profError });

        if (profError || !profile) {
            console.error("Profile missing or error:", profError);
            throw new Error("Perfil de usuario no encontrado");
        }

        let actualStudentId = profile.student_id; // Just in case it gets added
        if (profile.role === 'student' && !actualStudentId) {
            actualStudentId = await PulseService._getStudentId(profile.id) || undefined;
        }

        console.timeEnd('login');
        return {
            ...defaultAcademySettings, // Safety fallback
            id: profile.id,
            email: profile.email,
            name: profile.name,
            role: profile.role as 'master' | 'student',
            academyId: profile.academy_id,
            avatarUrl: profile.avatar_url,
            studentId: actualStudentId
        } as UserProfile;
    },

    logout: async () => {
        console.log("Logging out...");
        await supabase.auth.signOut();
    },

    getCurrentUser: async (): Promise<UserProfile | null> => {
        try {
            console.log("getCurrentUser: checking session...");
            const { data: { session }, error: sessionError } = await supabase.auth.getSession();

            if (sessionError) {
                console.error("Session error:", sessionError);
                return null;
            }

            if (!session?.user) {
                console.log("No active session found.");
                return null;
            }

            console.log("Session found for user:", session.user.id);

            // Add a timeout or just be safe.
            // If the user was just created, profile might not exist yet if trigger is slow.
            // BUT registerStudent creates it manually now, so it should be there.
            // For Masters, trigger might be slow.

            console.log("getCurrentUser: Fetching profile for", session.user.id);
            const { data: profile, error: profError } = await supabase
                .from('profiles')
                .select('*')
                .eq('id', session.user.id)
                .maybeSingle(); // Use maybeSingle to avoid error if not found immediately

            console.log("getCurrentUser: Profile fetch result", { profile, profError });

            if (profError) {
                console.warn("Error fetching profile for current user:", profError);
                return null;
            }

            if (!profile) {
                console.warn("Session user exists but Profile not found (yet). Returning null to force re-login or wait.");
                // Ensure we don't return partial data or hang
                return null;
            }

            let actualStudentId = profile.student_id;
            if (profile.role === 'student' && !actualStudentId) {
                actualStudentId = await PulseService._getStudentId(profile.id) || undefined;
            }

            console.log("Profile found:", profile.role);
            return {
                ...defaultAcademySettings, // Safety fallback for types
                id: profile.id,
                email: profile.email,
                name: profile.name,
                role: profile.role as 'master' | 'student',
                academyId: profile.academy_id,
                avatarUrl: profile.avatar_url,
                studentId: actualStudentId
            } as UserProfile;

        } catch (e) {
            console.error("Unexpected error in getCurrentUser:", e);
            return null;
        }
    },

    // --- PRIVATE HELPERS ---

    _getStudentId: async (userId: string): Promise<string | null> => {
        try {
            const { data, error } = await supabase
                .from('students')
                .select('id')
                .eq('user_id', userId)
                .limit(1)
                .maybeSingle();

            if (error || !data) return null;
            return data.id;
        } catch (e) {
            console.warn("_getStudentId error:", e);
            return null;
        }
    },

    // --- DATA ACCESS LAYER ---

    getAcademySettings: async (academyId?: string): Promise<AcademySettings> => {
        if (!academyId) return defaultAcademySettings;

        const { data, error } = await supabase
            .from('academies')
            .select('*')
            .eq('id', academyId)
            .single();

        if (error || !data) return defaultAcademySettings;

        const returnedSettings = data.settings || {};

        // Merge missing crucial settings
        const mergedSettings = { ...defaultAcademySettings, ...returnedSettings };
        if (!mergedSettings.ranks || mergedSettings.ranks.length === 0) {
            mergedSettings.ranks = defaultAcademySettings.ranks;
        }
        if (!mergedSettings.paymentSettings || !mergedSettings.paymentSettings.monthlyTuition) {
            mergedSettings.paymentSettings = { ...defaultAcademySettings.paymentSettings, ...mergedSettings.paymentSettings };
            // Ensure values aren't 0 if they shouldn't be
            if (!mergedSettings.paymentSettings.monthlyTuition) mergedSettings.paymentSettings.monthlyTuition = 500;
        }

        return {
            ...mergedSettings,
            id: data.id,
            name: data.name,
            code: data.code,
            ownerId: data.owner_id
        } as AcademySettings;
    },

    // --- OPTIMIZED FETCH METHODS (Role-Based) ---

    getStudentById: async (studentId: string): Promise<Student | null> => {
        if (!studentId) return null;

        try {
            // If the ID passed is actually a User ID (Auth ID), we might fail to find it if we search by 'id' (Student ID).
            // Since we are fixing logic to be robust, let's try to match either.
            // BUT the method name is getStudentById. 
            // Let's assume the caller MIGHT pass a User ID if they are confused.

            const { data, error } = await supabase
                .from('students')
                .select('*')
                .eq('id', studentId)
                .maybeSingle();

            if (data) {
                return {
                    id: data.id,
                    userId: data.user_id,
                    academyId: data.academy_id,
                    name: data.name,
                    email: data.email,
                    status: data.status,
                    rankId: data.rank_id,
                    balance: data.balance,
                    attendance: data.attendance_data?.total || 0,
                    attendanceHistory: data.attendance_data?.history || [],
                    ...data.details
                } as Student;
            }

            // Fallback: Try searching by user_id just in case
            const { data: byUser, error: errByUser } = await supabase
                .from('students')
                .select('*')
                .eq('user_id', studentId)
                .maybeSingle();

            if (byUser) {
                return {
                    id: byUser.id,
                    userId: byUser.user_id,
                    academyId: byUser.academy_id,
                    name: byUser.name,
                    email: byUser.email,
                    status: byUser.status,
                    rankId: byUser.rank_id,
                    balance: byUser.balance,
                    attendance: byUser.attendance_data?.total || 0,
                    attendanceHistory: byUser.attendance_data?.history || [],
                    ...byUser.details
                } as Student;
            }
        } catch (e) {
            console.warn("getStudentById error (swallowed):", e);
        }

        return null;
    },

    getPaymentsByStudent: async (userIdOrStudentId: string): Promise<TuitionRecord[]> => {
        if (!userIdOrStudentId) return [];

        try {
            // 1. Resolve exact Student ID from the User ID (Auth UID)
            let targetStudentId = userIdOrStudentId;

            // Try to find a student record where user_id matches given ID
            const { data: studentByUser } = await supabase
                .from('students')
                .select('id')
                .eq('user_id', userIdOrStudentId)
                .maybeSingle();

            if (studentByUser) {
                targetStudentId = studentByUser.id;
            }

            // 2. Query Payments with Student Data
            const { data, error } = await supabase
                .from('payments')
                .select('*, students(first_name, last_name, name, details)')
                .eq('student_id', targetStudentId);

            if (error || !data) return [];

            return data.map(row => {
                const s = row.students as any;
                let fetchedName: string | undefined = undefined;
                if (s) {
                    if (s.first_name) {
                        fetchedName = `${s.first_name} ${s.last_name || ''}`.trim();
                    } else if (s.name) {
                        fetchedName = s.name;
                    } else if (s.details?.name) {
                        fetchedName = s.details.name;
                    }
                }

                return {
                    ...row.details,
                    id: row.id,
                    academyId: row.academy_id,
                    studentId: row.student_id,
                    amount: row.amount,
                    status: row.status,
                    dueDate: row.due_date,
                    paymentDate: row.payment_date,
                    concept: row.concept,
                    studentName: fetchedName || row.details?.studentName || 'Estudiante'
                } as TuitionRecord;
            });
        } catch (e) {
            console.warn("getPaymentsByStudent error (swallowed):", e);
            return [];
        }
    },

    getStudents: async (academyId?: string): Promise<Student[]> => {
        if (!academyId) return [];
        const { data, error } = await supabase
            .from('students')
            .select('*')
            .eq('academy_id', academyId);

        if (error) throw error;
        if (!data) return [];

        return data.map(row => {
            // Hybrid mapping: check for direct columns or fallback to details
            // Ideally we migrate completely to columns, but for safety we check both.
            return {
                id: row.id,
                userId: row.user_id,
                academyId: row.academy_id,

                // Core Identity
                name: row.first_name ? `${row.first_name} ${row.last_name || ''}`.trim() : (row.name || row.details?.name || 'Sin Nombre'),
                email: row.email,

                // Status & Rank
                status: row.status,
                rankId: row.rank_id,
                rank: row.details?.rank || 'White Belt', // Fallback if not relational yet
                rankColor: row.details?.rankColor || 'white',

                // Financials
                balance: row.balance,

                // Attendance
                attendance: row.attendance_data?.total || 0,
                attendanceHistory: row.attendance_data?.history || [],
                lastAttendance: row.details?.lastAttendance,

                // Details Spread (Legacy support)
                ...row.details,

                // Explicit Overrides to ensure types match
                birthDate: row.birth_date || row.details?.birthDate,
                cellPhone: row.phone || row.details?.cellPhone,
                age: row.details?.age // Calculated or stored
            } as Student;
        });
    },

    getClasses: async (academyId?: string): Promise<ClassCategory[]> => {
        if (!academyId) return [];
        const { data, error } = await supabase
            .from('classes')
            .select('*')
            .eq('academy_id', academyId);

        if (error) throw error;
        if (!data) return [];

        return data.map(row => ({
            id: row.id,
            academyId: row.academy_id,
            name: row.name,
            instructor: row.instructor,
            studentIds: row.enrolled_student_ids || [],
            ...row.schedule_config
        })) as ClassCategory[];
    },

    getEvents: async (academyId?: string): Promise<Event[]> => {
        if (!academyId) return [];
        const { data, error } = await supabase
            .from('events')
            .select('*')
            .eq('academy_id', academyId);

        if (error) throw error;
        if (!data) return [];

        return data.map(row => ({
            id: row.id,
            academyId: row.academy_id,
            title: row.title,
            start: new Date(row.start_time),
            end: new Date(row.end_time),
            ...row.details,
            registrants: row.registrant_ids || [],
            type: row.type
        })) as Event[];
    },

    getLibrary: async (academyId?: string): Promise<LibraryResource[]> => {
        if (!academyId) return [];
        const { data } = await supabase.from('library').select('*').eq('academy_id', academyId);
        return (data || []).map(row => ({
            id: row.id,
            academyId: row.academy_id,
            title: row.title,
            category: row.category,
            videoUrl: row.url,
            ...row.details
        })) as LibraryResource[];
    },

    getPayments: async (userId: string, role: string): Promise<TuitionRecord[]> => {
        if (!userId) return [];
        // Fixed: Added 'name' and 'details' to the select so we can map studentName correctly
        let query = supabase.from('payments').select('*, students(first_name, last_name, group_id, name, details)');

        if (role === 'student') {
            // Rely entirely on Supabase RLS policies to accurately filter payments for the authenticated student.
            // This avoids missing records if the manual studentId lookup is delayed or throws an error.
            console.log("getPayments: Fetching payments securely using RLS for student", userId);


        } else if (role === 'master') {
            // 1. Get Academy ID from Profile
            const { data: profile, error: profileError } = await supabase
                .from('profiles')
                .select('academy_id')
                .eq('id', userId)
                .single();

            if (profileError || !profile?.academy_id) {
                console.warn("getPayments: Master has no academy_id", userId);
                return [];
            }

            // 2. Filter payments by academy_id
            query = query.eq('academy_id', profile.academy_id);
        } else {
            return [];
        }

        const { data, error } = await query;

        if (error) throw error;
        if (!data) return [];

        return data.map(row => {
            const s = row.students as any;
            let studentName: string | undefined = undefined;
            if (s) {
                if (s.first_name) {
                    studentName = `${s.first_name} ${s.last_name || ''}`.trim();
                } else if (s.name) {
                    studentName = s.name;
                } else if (s.details?.name) {
                    studentName = s.details.name;
                }
            }

            return {
                ...row.details,
                id: row.id,
                academyId: row.academy_id,
                studentId: row.student_id,
                amount: row.amount,
                status: row.status,
                dueDate: row.due_date,
                paymentDate: row.payment_date,
                concept: row.concept,
                studentName: studentName || row.details?.studentName || 'Estudiante' // Forces live relational name
            } as TuitionRecord;
        });
    },

    getExpenses: async (academyId?: string): Promise<Expense[]> => {
        if (!academyId) return [];
        try {
            // Check if 'expenses' table exists implies we just try to query it.
            // If it doesn't, Supabase throws 404 or structure error.
            const { data, error } = await supabase
                .from('expenses')
                .select('*')
                .eq('academy_id', academyId);

            if (error) {
                // If table missing, return empty (don't crash)
                console.warn("getExpenses: Table likely missing or empty", error.message);
                return [];
            }

            if (!data) return [];

            return data.map(row => ({
                id: row.id,
                academyId: row.academy_id,
                description: row.description,
                amount: row.amount,
                date: row.date || row.created_at, // Fallback
                category: row.category || 'General',
                paymentMethod: row.payment_method || 'Cash',
                status: row.status || 'paid'
            })) as Expense[];

        } catch (e) {
            console.warn("getExpenses error (swallowed):", e);
            return [];
        }
    },

    // --- WRITE METHODS ---

    saveAcademySettings: async (settings: AcademySettings) => {
        const { error } = await supabase
            .from('academies')
            .update({
                name: settings.name,
                settings: settings
            })
            .eq('id', settings.id);
        if (error) throw error;
    },

    saveStudents: async (students: Student[]) => {
        if (!students || students.length === 0) return;

        // Loop and update individually to ensure we never overwrite or nullify columns like `user_id`
        // due to PostgREST bulk-upsert limitations with omitted fields.
        for (const s of students) {
            const details = { ...s };
            delete (details as any).id;
            delete (details as any).userId;
            delete (details as any).academyId;
            delete (details as any).name;
            delete (details as any).email;
            delete (details as any).status;
            delete (details as any).rankId;
            delete (details as any).balance;
            delete (details as any).attendance;
            delete (details as any).attendanceHistory;

            const payload: any = {
                name: s.name,
                status: s.status,
                rank_id: s.rankId || null,
                balance: s.balance,
                attendance_data: { total: s.attendance, history: s.attendanceHistory },
                details: details
            };

            if (s.email) payload.email = s.email;
            // Never touch user_id in routine updates. It's set once by the PG trigger permanently.

            const { error } = await supabase.from('students').update(payload).eq('id', s.id);

            if (error) {
                console.error("Supabase update STUDENT error for ID", s.id, error);
                throw error;
            }
        }
    },

    saveClasses: async (classes: ClassCategory[]) => {
        if (!classes || classes.length === 0) return;
        const mapped = classes.map(c => {
            const config = { ...c };
            delete (config as any).id;
            delete (config as any).academyId;
            delete (config as any).name;
            delete (config as any).instructor;
            delete (config as any).studentIds;

            return {
                id: c.id,
                academy_id: c.academyId,
                name: c.name,
                instructor: c.instructor,
                enrolled_student_ids: c.studentIds,
                schedule_config: config
            };
        });

        const { error } = await supabase.from('classes').upsert(mapped);
        if (error) throw error;
    },

    deleteClass: async (classId: string) => {
        const { error } = await supabase.from('classes').delete().eq('id', classId);
        if (error) throw error;
    },

    saveEvents: async (events: Event[]) => {
        if (!events || events.length === 0) return;
        const mapped = events.map(e => {
            const details = { ...e };
            delete (details as any).id;
            delete (details as any).academyId;
            delete (details as any).title;
            delete (details as any).start;
            delete (details as any).end;
            delete (details as any).type;
            delete (details as any).registrants;

            return {
                id: e.id,
                academy_id: e.academyId,
                title: e.title,
                start_time: e.start?.toISOString(),
                end_time: e.end?.toISOString(),
                type: e.type,
                registrant_ids: e.registrants,
                details: details
            };
        });

        const { error } = await supabase.from('events').upsert(mapped);
        if (error) throw error;
    },

    savePayments: async (payments: TuitionRecord[]) => {
        if (!payments || payments.length === 0) return;
        const mapped = payments.map(p => {
            const details = { ...p };
            delete (details as any).id;
            delete (details as any).academyId;
            delete (details as any).studentId;
            delete (details as any).amount;
            delete (details as any).status;
            delete (details as any).dueDate;
            delete (details as any).paymentDate;
            delete (details as any).concept;

            return {
                id: p.id,
                academy_id: p.academyId,
                student_id: p.studentId,
                amount: p.amount,
                status: p.status,
                due_date: p.dueDate,
                payment_date: p.paymentDate,
                concept: p.concept,
                details: details
            };
        });

        const { error } = await supabase.from('payments').upsert(mapped);
        if (error) throw error;
    },

    deletePayment: async (recordId: string) => {
        const { error } = await supabase.from('payments').delete().eq('id', recordId);
        if (error) throw error;
    },

    saveExpense: async (expense: Expense) => {
        // Safe Attempt
        try {
            const { error } = await supabase.from('expenses').upsert({
                id: expense.id,
                academy_id: expense.academyId,
                description: expense.description,
                amount: expense.amount,
                date: expense.date,
                category: expense.category,
                payment_method: expense.paymentMethod,
                status: expense.status
            });
            if (error) throw error;
        } catch (e) {
            console.error("Failed to save expense (table missing?)", e);
            throw e;
        }
    },

    deleteExpense: async (id: string) => {
        try {
            const { error } = await supabase.from('expenses').delete().eq('id', id);
            if (error) throw error;
        } catch (e) {
            console.error("Failed to delete expense", e);
            throw e;
        }
    },

    saveLibrary: async (resources: LibraryResource[]) => {
        for (const r of resources) {
            const details = { ...r };
            delete (details as any).id;
            delete (details as any).academyId;
            delete (details as any).title;
            delete (details as any).category;
            delete (details as any).videoUrl;

            const { error } = await supabase.from('library').upsert({
                id: r.id,
                academy_id: r.academyId,
                title: r.title,
                category: r.category,
                url: r.videoUrl,
                details: details
            });
            if (error) throw error;
        }
    },

    // --- BUSINESS LOGIC ---

    enrollStudentInClass: async (studentId: string, classId: string, students: Student[], classes: ClassCategory[]) => {
        // Logic should now likely be server-side or update both via save.
        // For keeping "Business Logic Intact" with minimal refactor, we can modify the objects
        // and then call saveClasses() / saveStudents(). 
        // Re-using the logic from the old file would be best.

        // Fetch fresh if needed, or use passed in.
        // NOTE: The previous logic updated arrays in memory and returned them.
        // The calling component then likely called setClasses/setStudents.
        // BUT also, the previous logic did NOT save inside this helper.
        // We will keep the helper as PURE logic or logic + save?
        // Old: return { updatedClasses, updatedStudents }
        // The calling code typically does: setUser(..), etc.
        // We probably need to verify where this is called.

        // Re-implementing the pure logic part:
        const updatedClasses = classes.map(c => {
            if (c.id === classId && !c.studentIds.includes(studentId)) {
                return { ...c, studentIds: [...c.studentIds, studentId], studentCount: c.studentCount + 1 };
            }
            return c;
        });

        const updatedStudents = students.map(s => {
            if (s.id === studentId) {
                const currentClasses = s.classesId || [];
                if (!currentClasses.includes(classId)) {
                    return { ...s, classesId: [...currentClasses, classId] };
                }
            }
            return s;
        });

        // AND SAVE TO DB because we moved persistence to DB
        // But the consuming component might expect to just update state.
        // Use `saveClasses` and `saveStudents` here for safety.
        await PulseService.saveClasses(updatedClasses); // Only saves modified ones ideally, but our simple impl saves all.
        await PulseService.saveStudents(updatedStudents);

        return { updatedClasses, updatedStudents };
    },

    unenrollStudentFromClass: async (studentId: string, classId: string, students: Student[], classes: ClassCategory[]) => {
        const updatedClasses = classes.map(c => {
            if (c.id === classId) {
                return {
                    ...c,
                    studentIds: c.studentIds.filter(id => id !== studentId),
                    studentCount: Math.max(0, c.studentCount - 1)
                };
            }
            return c;
        });

        const updatedStudents = students.map(s => {
            if (s.id === studentId && s.classesId) {
                return { ...s, classesId: s.classesId.filter(id => id !== classId) };
            }
            return s;
        });

        await PulseService.saveClasses(updatedClasses);
        await PulseService.saveStudents(updatedStudents);

        return { updatedClasses, updatedStudents };
    }

    // ... Any other missing methods? 
    // updateEventRegistrants, registerStudentForEvent, updatePaymentRecord
    // We should implement them similarly.
};

// Add missing methods to object 
Object.assign(PulseService, {
    registerStudentForEvent: async (studentId: string, eventId: string, events: Event[]) => {
        const updatedEvents = events.map(e => {
            if (e.id === eventId && !e.registrants?.includes(studentId)) {
                return {
                    ...e,
                    registrants: [...(e.registrants || []), studentId],
                    registeredCount: (e.registrants?.length || 0) + 1
                };
            }
            return e;
        });
        await PulseService.saveEvents(updatedEvents);
        return updatedEvents;
    },

    updateEventRegistrants: async (events: Event[], eventId: string, studentIds: string[]) => {
        const updatedEvents = events.map(e => {
            if (e.id === eventId) {
                return {
                    ...e,
                    registrants: studentIds,
                    registeredCount: studentIds.length
                };
            }
            return e;
        });
        await PulseService.saveEvents(updatedEvents);
        return updatedEvents;
    },

    updatePaymentRecord: async (updatedRecord: TuitionRecord) => {
        await PulseService.savePayments([updatedRecord]);
    }
});